name: Docker Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  docker-build:
    strategy:
      fail-fast: false
      matrix:
        from:
          - alpine
          - h8300
          - ubuntu
          - v850
          # EOL
          # - centos
    uses: ./.github/workflows/reusable-docker-build.yml
    with:
      publish: ${{ github.event_name != 'pull_request' }}
      from: ${{ matrix.from }}
    secrets: inherit
